# yash project, the directory structure a bit sloppy but will fix for future labs
CC=gcc

# compiler flags
# -g adds debugging info
CFLAGS = -g

# the build target executable


yash: yash.c functions.c




 
